### ISSUE TITLE
请问ios的怎么加载进去呢？ 

### ISSUE THREAD

**Issue by 13122310958** [offbye/cordova-plugin-alipay#1]
Cannot find resource file [project name]/plugins/cordova-plugin-alipay/src/lib/AlipaySDK.bundle  " for plugin cordova-plugin-alipay in iOS platform

**Comment by 13122310958** [comment]
有个配置的bug ： 
应该是这样才对
`<resource-file src="src/ios/lib/AlipaySDK.bundle"/>`

**Comment by 13122310958** [comment]
请问你遇到这个问题么？ 


Undefined symbols for architecture armv7:
  "_inflate", referenced from:
      -[APayProcessor gzipDecompressWithData:] in AlipaySDK
  "_deflate", referenced from:
      -[APayProcessor gzipCompressWithData:] in AlipaySDK
      +[ASSCommonUtils gzipData:] in AlipaySDK
      +[DTGZipUtil compressGZip:] in AlipaySDK
  "_inflateEnd", referenced from:
      -[APayProcessor gzipDecompressWithData:] in AlipaySDK
  "_deflateInit2_", referenced from:
      -[APayProcessor gzipCompressWithData:] in AlipaySDK
      +[ASSCommonUtils gzipData:] in AlipaySDK
      +[DTGZipUtil compressGZip:] in AlipaySDK
  "_inflateInit2_", referenced from:
      -[APayProcessor gzipDecompressWithData:] in AlipaySDK
  "_deflateEnd", referenced from:
      -[APayProcessor gzipCompressWithData:] in AlipaySDK
      +[ASSCommonUtils gzipData:] in AlipaySDK
      +[DTGZipUtil compressGZip:] in AlipaySDK
ld: symbol(s) not found for architecture armv7


Undefined symbols for architecture arm64:
  "_inflate", referenced from:
      -[APayProcessor gzipDecompressWithData:] in AlipaySDK
  "_deflate", referenced from:
      -[APayProcessor gzipCompressWithData:] in AlipaySDK
      +[ASSCommonUtils gzipData:] in AlipaySDK
      +[DTGZipUtil compressGZip:] in AlipaySDK
  "_inflateEnd", referenced from:
      -[APayProcessor gzipDecompressWithData:] in AlipaySDK
  "_deflateInit2_", referenced from:
      -[APayProcessor gzipCompressWithData:] in AlipaySDK
      +[ASSCommonUtils gzipData:] in AlipaySDK
      +[DTGZipUtil compressGZip:] in AlipaySDK
  "_inflateInit2_", referenced from:
      -[APayProcessor gzipDecompressWithData:] in AlipaySDK
  "_deflateEnd", referenced from:
      -[APayProcessor gzipCompressWithData:] in AlipaySDK
      +[ASSCommonUtils gzipData:] in AlipaySDK
      +[DTGZipUtil compressGZip:] in AlipaySDK
ld: symbol(s) not found for architecture arm64

我是尝试了：ionic build ios --device --release -v

发现还是我无法编译通过。  android的可以通过。 麻烦帮我看下了么？谢谢！

**Comment by h2oiswater** [comment]
加上这个就行了吗？ 是不是加载根目录的config.xml随便一个位置
然后再下载一边
我加在了config.xml里面
再下载还是提示这个

**Comment by h2oiswater** [comment]
还是说把plugin.xml 
从 `<resource-file src="src/lib/AlipaySDK.bundle"/>` 
改成 `<resource-file src="src/ios/lib/AlipaySDK.bundle"/>`
然后还需要操作什么吗

**Comment by h2oiswater** [comment]
@13122310958 是不是要手动去XCode引入一些文件

**Comment by jerrylovestsoft** [comment]
你好，我用了这个插件以后，IOS无法使用，运行直接报错，Error: Uh oh!
Cannot find resource file "/Users/stsofthfweb/cycarIos/plugins/cordova-plugin-offbye-alipay/src/lib/AlipaySDK.bundle" for plugin cordova-plugin-offbye-alipay in iOS platform 一直困扰我很多天了，找不到解决方案，求大神指点，安卓里面我是可以使用的

**Comment by 13122310958** [comment]
是的。 要手工引入才行
